import { createSystem, defaultConfig, defineConfig } from "@chakra-ui/react"

const config = defineConfig({
  theme: {
    tokens: {
      fonts: {
        heading: { value: "'Plus Jakarta Sans', system-ui, sans-serif" },
        body:    { value: "'Plus Jakarta Sans', system-ui, sans-serif" },
        mono:    { value: "'JetBrains Mono', ui-monospace, monospace" },
      },
      colors: {
        brand: {
          50:  { value: "#fff7ed" },
          100: { value: "#ffedd5" },
          200: { value: "#fed7aa" },
          300: { value: "#fdba74" },
          400: { value: "#fb923c" },
          500: { value: "#f97316" },
          600: { value: "#ea580c" },
          700: { value: "#c2410c" },
          800: { value: "#9a3412" },
          900: { value: "#7c2d12" },
          950: { value: "#431407" },
        },
        success: {
          50:  { value: "#f0fdf4" },
          100: { value: "#dcfce7" },
          200: { value: "#bbf7d0" },
          300: { value: "#86efac" },
          400: { value: "#4ade80" },
          500: { value: "#22c55e" },
          600: { value: "#16a34a" },
          700: { value: "#15803d" },
          800: { value: "#166534" },
          900: { value: "#14532d" },
          950: { value: "#052e16" },
        },
        danger: {
          50:  { value: "#fef2f2" },
          100: { value: "#fee2e2" },
          200: { value: "#fecaca" },
          300: { value: "#fca5a5" },
          400: { value: "#f87171" },
          500: { value: "#ef4444" },
          600: { value: "#dc2626" },
          700: { value: "#b91c1c" },
          800: { value: "#991b1b" },
          900: { value: "#7f1d1d" },
          950: { value: "#450a0a" },
        },
        info: {
          50:  { value: "#eff6ff" },
          100: { value: "#dbeafe" },
          200: { value: "#bfdbfe" },
          300: { value: "#93c5fd" },
          400: { value: "#60a5fa" },
          500: { value: "#3b82f6" },
          600: { value: "#2563eb" },
          700: { value: "#1d4ed8" },
          800: { value: "#1e40af" },
          900: { value: "#1e3a8a" },
          950: { value: "#172554" },
        },
        neutral: {
          50:  { value: "#fafaf9" },
          100: { value: "#f5f5f4" },
          200: { value: "#e7e5e4" },
          300: { value: "#d6d3d1" },
          400: { value: "#a8a29e" },
          500: { value: "#78716c" },
          600: { value: "#57534e" },
          700: { value: "#44403c" },
          800: { value: "#292524" },
          900: { value: "#1c1917" },
          950: { value: "#0c0a09" },
        },
        amber: {
          50:  { value: "#fffbeb" },
          100: { value: "#fef3c7" },
          200: { value: "#fde68a" },
          300: { value: "#fcd34d" },
          400: { value: "#fbbf24" },
          500: { value: "#f59e0b" },
          600: { value: "#d97706" },
          700: { value: "#b45309" },
          800: { value: "#92400e" },
          900: { value: "#78350f" },
          950: { value: "#451a03" },
        },
        chart: {
          prediction:       { value: "#eab308" },
          predictionBorder: { value: "#ca8a04" },
          tick:             { value: "#9ca3af" },
          gridX:            { value: "#f9fafb" },
          gridY:            { value: "#f3f4f6" },
          tooltipBg:        { value: "#1f2937" },
          tooltipTitle:     { value: "#f9fafb" },
          tooltipBody:      { value: "#d1d5db" },
          tooltipBorder:    { value: "#374151" },
          swatchInactive:   { value: "#d1d5db" },
          series: {
            0:  { value: "#1d4ed8" },
            1:  { value: "#dc2626" },
            2:  { value: "#16a34a" },
            3:  { value: "#d97706" },
            4:  { value: "#7c3aed" },
            5:  { value: "#0891b2" },
            6:  { value: "#be185d" },
            7:  { value: "#059669" },
            8:  { value: "#ea580c" },
            9:  { value: "#6366f1" },
            10: { value: "#84cc16" },
            11: { value: "#f43f5e" },
            12: { value: "#14b8a6" },
            13: { value: "#a855f7" },
            14: { value: "#fb923c" },
            15: { value: "#0ea5e9" },
            16: { value: "#10b981" },
            17: { value: "#e11d48" },
            18: { value: "#8b5cf6" },
            19: { value: "#22c55e" },
          },
        },
      },
      radii: {
        field: { value: "{radii.2xl}" },
        card:  { value: "{radii.2xl}" },
        pill:  { value: "{radii.full}" },
      },
      shadows: {
        card:           { value: "{shadows.sm}" },
        cardElevated:   { value: "{shadows.md}" },
        menu:           { value: "{shadows.lg}" },
        focusRingBrand: { value: "0 0 0 2px {colors.brand.200}" },
        focusRingInfo:  { value: "0 0 0 2px {colors.info.400}" },
      },
    },
    semanticTokens: {
      colors: {
        surface: {
          base:    { value: "{colors.white}" },
          muted:   { value: "{colors.neutral.50}" },
          subtle:  { value: "{colors.neutral.100}" },
          inverse: { value: "{colors.neutral.900}" },
          overlay: { value: "{colors.blackAlpha.500}" },
        },
        text: {
          primary:   { value: "{colors.neutral.900}" },
          secondary: { value: "{colors.neutral.500}" },
          muted:     { value: "{colors.neutral.400}" },
          onInverse: { value: "{colors.white}" },
        },
        border: {
          subtle:  { value: "{colors.neutral.100}" },
          default: { value: "{colors.neutral.200}" },
          strong:  { value: "{colors.neutral.300}" },
        },
        accent: {
          warning: {
            bg:     { value: "{colors.amber.50}" },
            border: { value: "{colors.amber.200}" },
            fg:     { value: "{colors.amber.700}" },
            solid:  { value: "{colors.amber.400}" },
          },
        },
      },
    },
    textStyles: {
      heading: {
        page:    { value: { fontSize: "2xl", fontWeight: "bold", lineHeight: "tight", letterSpacing: "tight" } },
        section: { value: { fontSize: "xl", fontWeight: "bold", lineHeight: "tight", letterSpacing: "tight" } },
      },
      metaLabel: {
        value: {
          fontSize: "xs",
          fontWeight: "semibold",
          textTransform: "uppercase",
          letterSpacing: "widest",
          color: "text.secondary",
        },
      },
      body: {
        sm: { value: { fontSize: "sm", lineHeight: "normal" } },
        xs: { value: { fontSize: "xs", lineHeight: "normal" } },
      },
      monoPill: {
        value: {
          fontFamily: "mono",
          fontSize: "xs",
          fontWeight: "bold",
          letterSpacing: "widest",
        },
      },
    },
    layerStyles: {
      card: {
        value: {
          bg: "surface.base",
          borderWidth: "1px",
          borderColor: "border.default",
          borderRadius: "card",
          boxShadow: "card",
        },
      },
      cardElevated: {
        value: {
          bg: "surface.base",
          borderWidth: "1px",
          borderColor: "border.default",
          borderRadius: "card",
          boxShadow: "cardElevated",
        },
      },
      field: {
        value: {
          borderWidth: "1px",
          borderColor: "border.default",
          borderRadius: "field",
          bg: "surface.subtle",
          color: "text.primary",
          _placeholder: { color: "text.muted" },
        },
      },
      pillMuted: {
        value: {
          bg: "surface.subtle",
          color: "text.muted",
          borderRadius: "pill",
        },
      },
    },
  },
})

export const system = createSystem(defaultConfig, config)
